services:
  instadownloaderbot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:5000:3000"
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app:Z
    command: "sh -c 'test -d node_modules || npm install && npm start'"