services:
  instadownloaderbot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app:Z
    restart: always
    command: "sh -c 'test -d node_modules || npm install && npm start'"