services:
  instadownloaderbot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.development
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app:Z
    command: "sh -c 'test -d node_modules || npm install && npm run dev'"