name: Github InstaDownloaderBot Deploy

on:
  push:
    branches: ["main", "dev"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: rsync deployments
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete
          path: ./*
          remote_path: ~/insta-downloader-graphql
          remote_host: "${{ secrets.EC2_PUBLIC_IP }}"
          remote_user: ubuntu
          remote_key: "${{ secrets.EC2_SSH_KEY }}"