name: Github InstaDownloaderBot Deploy

on:
  push:
    branches: ["main", "dev"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
      
      - name: Connect to EC2 and execute commands
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.AWS_USER }}@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
          echo "Connected to EC2!"
          # Add your commands here, e.g., pulling the latest changes
          git pull origin main
          EOF