name: Github InstaDownloaderBot Deploy

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Copy folder to EC2
        run: |
          scp -o StrictHostKeyChecking=no -r "./InstaDownloaderBot (GraphQL)" ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "mkdir -p '~/InstaDownloaderBot (GraphQL)'"

      - name: Run deployment commands on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} 'bash -s' <<EOF
          cd "~/InstaDownloaderBot (GraphQL)"
          npm install
          npm run prod
          ngrok http 3000
          EOF