name: Github InstaDownloaderBot Deploy

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: rsync deployments
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete
          path: ./*
          remote_path: ~/insta-downloader-graphql
          remote_host: "${{ secrets.AWS_IPV4_DNS }}"
          remote_user: "${{ secrets.AWS_USER }}"
          remote_key: "${{ secrets.AWS_PRIVATE_KEY }}"